project:
  type: book
  output-dir: docs

book:
  title: "Web Mapping and Geovisualisation"
  author: "Gabriele Filomena and Elisabetta Pietrostefani"
  date: today

  page-footer:
    left: |
      Web Mapping and Geovisualisation by Gabriele Filomena and Elisabetta Pietrostefani.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  search: true
  site-url:  https://gdsl-ul.github.io/wma
  repo-url: https://github.com/GDSL-UL/wma
  repo-actions: [edit]
  sidebar:
    style: docked
    background: light
  downloads: [pdf]
  chapters:
    - index.qmd
    - general/structure.qmd
    - general/overview.qmd
    - general/assessments.qmd
    - general/pythonwin.qmd
    - general/pythonmac.qmd
    - labs/w01_intro.ipynb
    - labs/w02_maps.ipynb
    - labs/w03_webArch.ipynb
    - labs/w04_dataArch.ipynb
    - labs/w05_interactive.ipynb
    - labs/w07_OSM.ipynb
    
bibliography: references.bib

format:
  html:
    theme: zephyr
    css: styles.css
  pdf:
    documentclass: scrreprt

editor: visual



