project:
  type: book
  output-dir: docs

book:
  title: "Web Mapping and Analysis"
  author: "Elisabetta Pietrostefani and Dani Arribas-Bel"
  date: today

  page-footer:
    left: |
      Web Mapping and Analysis was written by Elisabetta Pietrostefani and Dani Arribas-Bel.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  search: true
  site-url:  https://gdsl-ul.github.io/wma
  repo-url: https://github.com/GDSL-UL/wma
  repo-actions: [edit]
  sharing: [twitter, facebook]
  twitter-card:
    creator: "@EPietrostefani"
  sidebar:
    style: docked
    background: light
  downloads: [pdf, epub]
  chapters:
    - index.qmd
    - general/structure.qmd
    - general/overview.qmd
    - general/assess.qmd
    - labs/w01_introduction.qmd
    - labs/w01_refresher.qmd
    - labs/w02_maps.qmd
    - labs/w03_dataArch.qmd
    - labs/w04_webArch.qmd
    - labs/w05_interactive.qmd
    
bibliography: references.bib

format:
  html:
    theme: zephyr
    css: styles.css
  pdf:
    documentclass: scrreprt

editor: visual



