name: gis
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2023.12.12
  - expat=2.5.0
  - libffi=3.4.4
  - openssl=3.0.12
  - pip=23.3.1
  - python=3.11.5
  - setuptools=68.2.2
  - sqlite=3.41.2
  - tk=8.6.12
  - wheel=0.41.2
  - xz=5.4.5
  - zlib=1.2.13
  - pip:
      - affine==2.4.0
      - attrs==23.2.0
      - bleach==6.1.0
      - bokeh==3.3.4
      - branca==0.7.0
      - cartopy==0.22.0
      - census==0.8.21
      - certifi==2023.11.17
      - charset-normalizer==3.3.2
      - click==8.1.7
      - click-plugins==1.1.1pi
      - cligj==0.7.2
      - colorama==0.4.6
      - colorcet==3.0.1
      - contextily==1.5.0
      - contourpy==1.2.0
      - cycler==0.12.1
      - fiona==1.9.5
      - folium==0.15.1
      - fonttools==4.47.0
      - geographiclib==2.0
      - geopandas==0.14.1
      - geoplot==0.5.1
      - geopy==2.4.1
      - holoviews==1.18.1
      - hvplot==0.9.1
      - idna==3.6
      - install==1.3.5
      - jellyfish==0.11.2
      - jenkspy==0.4.0
      - jinja2==3.1.2
      - joblib==1.3.2
      - json5==0.9.14
      - kiwisolver==1.4.5
      - linkify-it-py==2.0.2
      - llvmlite==0.41.1
      - mapclassify==2.6.1
      - markdown==3.5.2
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - matplotlib==3.8.2
      - matplotlib-inline==0.1.6
      - mdit-py-plugins==0.4.0
      - mdurl==0.1.2
      - mercantile==1.2.1
      - movingpandas==0.17.2
      - networkx==3.2.1
      - numba==0.58.1
      - numpy==1.26.3
      - osmnx==1.8.1
      - packaging==23.2
      - pandas==2.1.4
      - panel==1.3.8
      - param==2.0.2
      - pillow==10.2.0
      - plotly==5.18.0
      - pyct==0.5.0
      - pyparsing==3.1.1
      - pyproj==3.6.1
      - pyshp==2.3.1
      - python-dateutil==2.8.2
      - pytz==2023.3.post1
      - pyviz-comms==3.0.1
      - pyyaml==6.0.1
      - rasterio==1.3.9
      - requests==2.31.0
      - rtree==1.1.0
      - scikit-learn==1.3.2
      - scipy==1.11.4
      - seaborn==0.13.1
      - shapely==2.0.2
      - six==1.16.0
      - snuggs==1.4.7
      - tenacity==8.2.3
      - threadpoolctl==3.2.0
      - tornado==6.4
      - tqdm==4.66.1
      - traitlets==5.14.1
      - typing-extensions==4.9.0
      - tzdata==2023.4
      - uc-micro-py==1.0.2
      - urllib3==2.1.0
      - us==3.1.1
      - websocket-client==1.7.0
      - xyzservices==2023.10.1
    
