# Introduction 

* Lab 2 can go in Lab 1 (Lab 2: Powerful examples \* Discussion about interactive map)

# Slides

HTML
PDF

* As a [pdf document](https://gdsl-ul.github.io/wma/lecture_02.pdf)

References:

For an excellent coverage of “visualisation literacy”, Chapter 11 of Andy Kirk’s “Data Visualisation” is a great start.
Lab: Getting up to speed for web mapping

# Lab: Powerful examples 

This lab has two main components: the first one will require you to find a partner and work together with her/him; and the second one will involve group discussion.

## Paired activity
In pairs, find three examples where web maps are used to communi- cate an idea. Complete the following sheet for each example:

* Substantive
  + Title: Title of the map/project
  + Author: Who is behind the project?
  + Big idea: a “one-liner” on what the project tries to accomplish – Message: what does the map try to get accross

* Technical
  + URL:
  + Interactivity: does the map let you interact with it in any
way? Yes/No
  + Zoomable: can you explore the map at different scales? Yes/No
  + Tooltips:
  + Basemap: Is there an underlying map providing geographical
context? Yes/No. If so, who is it provided by?
  + Technology: can you guess what technology does this map rely
on?

Post each sheet as a separate item on the Teams channel for Lab No.2
As an example, here’s the sheet for the project “A map of every building in America”

# Other

A comprehensive overview of computational notebooks and how they relate to modern scientific work is available on Ch.1 of the GDS book, currently in progress. https://geographicdata.science/book/notebooks/01_geospatial_computational_environment.html

A more recent overview of notebooks in Geography is available in Boeing & Arribas-Bel (2021)