# Technology Gallery

Dani Arribas-Bel

## Lecture - Technology gallery

In this session, we are flipping the roles: you will be leading a discussion on emerging technologies for web mapping. There is so much these days that is appearing, changing and evolving in the world of web mapping. Much of it is hype and quickly goes away; but not all. Some of these trends will go on to become the new standard in the coming years. Most of it builds on general concepts and technologies we have seen in this course. This session will give us all a taste of what might be around the corner!

### What is the “technology gallery”?
The technology gallery is a showcase of emerging technologies and projects in web mapping. This will cover several areas we have not had time to cover in the course, but that knowing about them might be useful for you.

Practically speaking, we will run the gallery as a series of lightning talks driven by students and moderated by the module leader.

### Do I need to do anything before the session?
Yes. There are three things you need to do before the day of the gallery:

- **Decide how you will work.** The recommended option is that you pair with two or three peer student and, together, complete the presentation. If you prefer it, you can do this task on your own.
- **Pick a project.** Have a look at the list of potential projects and choose one that picks your interest, and “claim” it by adding your name on “Student” column of the spreadsheet. If you know of a different project that might be a good fit, please speak to the module leader, there’s a good chance it’ll be fine.

You can find the spreadsheet with projects and sign up at:

Teams link to gallery spreadsheet to be updated

NOTE: you will need to be signed into the University of Liverpool Teams to be able to access it.

- **Prepare a lightning talk.** Once you have a partner in crime (or you have decided to work on your own) and a project picked, it’s time to get cracking. First, you will explore the project/tool, ideally play with it and experiment to get a first-hand feel of how it works and what its real potential is. Once you have a good idea, start thinking of a presentation to communicate what you have learnt. There is only two requirements:

The total time of the presentation needs to be two minutes max
If you use slides, no more than three
The presentation should cover the following aspects of your exploration:

- `Name of the project`
- `Background` - Who makes it? What is it for? How has it been used?
- `Availability` - How can you access it and use it? Is it a web tool? Does it work on the command line? Is it a - package for a programming language?
- `Areas of application` - What use cases is this good for? What would you recommend it for?
- `Review` - After using it a bit, what do you think of the project? Would you use it yourself? Would you recommend it?

Be creative in structuring your presentation. Do you want to team-present it with your team colleague? Absolutely. Would a .gif help get an idea across? Go for it! A live demo? Maybe, but remember it needs to fit into 2 minutes. The ligning talk is a super flexible format, make the most of it!

### How will the session work?

On the day of the session, have your presentation ready. We will run it as a live Teams video chat where each student will be able to share their own screen for the presentation.

## Lab - Assignment II clinic

Assignment clinic. Come to the lab and work on your assignment while collaborating with other students and being able to have direct support from module leader on the spot!
