
# Assignment II {.unnumbered}

-   **Title:** *Final Geovisualisation Project*.
-   **Type:** Coursework.
-   **Due: Thursday April  30th (2.00 pm) - Week 11**.
-   50% of the final mark.
-   Submission on Canvas, `.html` files only.

This assignment requires you to develop a final geovisualisation project on **spatial data set(s) of your choice**. To be successful, you will need to demonstrate your understanding not only of technical elements, but of the design process required to create a product that can communicate complex ideas effectively. This final product should be a geovisualisation interactive product (i.e., it should contain a cartographic, interactive visualisation) and should contain one analytical component developed further from the content presented in class, in relation to:
	
- Geographic/Street Network Analysis (week 6).
- Working with Raster Data (week 7).
- Working with  spatio-temporal mobility data, not necessarily urban (week 9).

Or, it should present:

- a Dashboard developed with `panel` (week 10) or `pydeck`.
	
To be successful, you will need to demonstrate your understanding not only of the technical aspects involved in the process but also of the conceptual notions underpinning them. Below are the required components for your submission:

1.  **Context and Problem**: Identify a research problem with a geographical connotation. Discuss concisely recent research around it in physical or human geography (around 7–8 references). Introduce how you will explore and visualise dimensions of the problem (e.g., gentrification, access to healthy food in cities, urban heat islands, etc.).
2.  **Data and Backend**: Include datasets containing spatial information or linkable to other spatial sources. Highlight the data/variables worth considering and their role in representing the problem. 
3.  **Design**: Create good looking static maps to represent your datasets, focusing on spatial units (e.g., buildings, cities). 
4.  **Assemblage**: Address design considerations, including the map’s extent, zoom levels, and variable visibility at different zoom levels. Ensure consistency and aesthetic appeal to build your final geovisualisation product.

## Expected Content

### Code

- Introductory Static Maps (1 to 3), presenting the topic and the geographic context.
- API requests (**optional**), data calls, and necessary data cleaning operations.
- An interactive final geovisualisation product
- All the necessary steps for building and refining the final geovisualisation product.

**You CANNOT employ for your main maps the following libraries: Holoviews, Geoviews, and Plotly**.
**DO not use data from Kaggle** 

### Text in Markdown Cells, 1,000 words, distributed across the notebook

- ~ 250 words introducing the research problem, the context, and existing recent research on the topic.
- ~ 250 words presenting and motivating the chosen data sources, in relation to your research problem. Here you should engage not only with what data you are using but why and what they bring to the dashboard. 
- ~ 200 words for the overall idea of the final geovisualisation device/medium. What do you want to communicate? What is the story you want to tell? **This final product should contain ONE analytical component developed further from the content presented in class, in relation to**:
	
	- Geographic/Street Network Analysis (week 6).
	- Working with Raster Data (week 7).
	- Working with  spatio-temporal mobility data, not necessarily urban (week 8).
	
	Or, it should present:
	
	- a Dashboard developed with `panel` (week 9) or `pydeck`.

- ~ 200 words where you describe your design choices around interactivity, including both cartographic elements (e.g. zooming, panning).
- ~ 100 words  to summarise your research problem and how you tackled it by means of geovisualisation tools (Conclusion).

## Evaluation
The assignment will be evaluated based on 3 main pillars, on which you will have to be successful to achieve a good mark:

1.  **Narrative**. The ability to identify and present a research problem, motivate and justify one's map, as well as the ability to bring each component of the assignment into a coherent whole that "fits together".
2.  **Map(s) design**.  It is very important to think through every step of preparing this assignment as if it was part of something bigger towards which it contributes.  Critically introduce every aspect considered when designing the map(s) andyour final product, by explicitly connecting it to the overall aim of the project. One should clearly and critically describe how they engaged with every design choice (e.g. adding certain widgets or interactivity functions).
3.   **Technical skills**. The ability to master Python scripting and technologies that allow one to create an interactive, informative and compelling geographic product, as well as to access interesting and sophisticated data sources.

## How is this assignment useful?

This assignment combines several elements that will help you improve critical aspects of web mapping:

-   **Design**: this is not about making maps, this is about making good maps. And behind every good map there is a set of conscious choices that you will have to think through to be successful (what map? what data? how to present the data? etc.).
-   **Technology**: at the end of the day, building good web maps requires familiarity with the state-of-the-art in terms of web mapping tools. In this assignment, you will need to demonstrate your mastery of some of the key tools that are leading both industry and academia.
-   **Presentation**: in many real-world contexts, your work is as good as it can come across to the audience it is intended to. This means that it is vital to be able to communicate not only what you are doing but why and on what building blocks it is based on.


