
# Check-list Assignment 2 #

- Make treasure of the feedback received for assignment 1. Do not make the same mistakes.
- Only one file -> `.html`
- Have a look at the template and procedure to incoporate the dashboard, prior to converting it to `.html` [here](https://github.com/GDSL-UL/wma/blob/main/templates/Assignment2_template.ipynb) and [here](https://gdsl-ul.github.io/wma/labs/w10_panelHTML.html).
- If, still, it doesn't work:
	- Use a screene recorder software to record yourself demonstrating the usage of the dashboard and its interactivity.
	- Upload the video on youtube or to a repository on Github.
	- Provide a Link to the video at the bottom of the assignment.
- See Examples from last year here (note: they do not render on Github) [here](https://github.com/GDSL-UL/wma/tree/main/examples/Dashboard);
- Still issues, not addressed by the [guidelines](https://gdsl-ul.github.io/wma/general/assignmentII.html)?  ask/check if anyone has asked arlready on Ms Teams.
- BEFORE SUBMISSION -> Go through your static file and check whether it is completed and rendered. Ask a friend to have a look at it on ather PC, or do it yourself.
