# Overview {.unnumbered}

## Aims

This module aims to provide hands-on experience and training in:
- The design and generation of (good looking) web-based mapping and geographical information tools.
- The use of software to access, analyse and visualize web-based geographical information.

## Learning Outcomes

By the end of the module, students should be able to:


(2) Visualise and represent geo-data through static and dynamic maps.
(2) Recognise and describe the component of web based mapping infrastructure.
(3) Collect Web-based data.
(1) Generate interactive maps and dashboards.
(4) Understand basic concepts of spatial network analysis.
(5) Manipulate geo-data through scripting in Python.

## Feedback

[*Formal assessment*](https://gdsl-ul.github.io/wma/assess.html). Two pieces of coursework (50%/50%). Equivalent to 2,500 words each

*Verbal face-to-face feedback*. Immediate face-to-face feedback will be provided during computer, discussion and clinic sessions in interaction with staff. This will take place in all live sessions during the semester.
*Teams Forum*. Asynchronous written feedback will be provided via Teams. Students are encouraged to contribute by asking and answering questions relating to the module content. Staff will monitor the forum Monday to Friday 9am-5pm, but it will be open to students to make contributions at all times. Response time will vary depending on the complexity of the question and staff availability.


