# Syllabus {.unnumbered}

**Week 1 GF** Central Teaching Lab: PC Teaching Centre BLUE ZONE (1 - 4pm)

-   Lecture: Introduction to the module

-   Lab: Powerful examples and Python Refresher

**Week 2 GF** Central Teaching Lab: PC Teaching Centre BLUE ZONE (1 - 4pm)

-   Lecture: Geovisualisation: Design Principles and Statistical Visualisation

-   Lab: Static Maps in Python.

**Week 3 GF** Central Teaching Lab: PC Teaching Centre BLUE ZONE (1 - 4pm)

-   Lecture: Interactive Maps

-   Lab: Interactive Maps with Folium.

**Week 4 EP** Central Teaching Lab: PC Teaching Centre BLUE ZONE (1 - 4pm)

-   Lecture: The Web's Architecture

-   Lab: Web Architectures and APIs in Python.

**Week 5 EP** Central Teaching Lab: PC Teaching Centre BLUE ZONE (2 - 4pm)

-   Lab only: Review & Assignment I clinic.

-   **Assignment I Due** 26th February 2.00pm

**Week 6 GF** Central Teaching Lab: PC Teaching Centre BLUE ZONE (1 - 4pm)

-   Lecture: OpenStreetMap Data & Spatial Network.

-   Lab: Retrieving Data From OpenStreetMap.

**Week 7 EP** Central Teaching Lab: PC Teaching Centre BLUE ZONE (1 - 4pm)

-   Lecture: From Pixels to Patterns: Visualising Satellite Image Classification

-   Lab: Satellite Image Classification in Python

**Week 8**

-   NO TEACHING

**Week 9 GF** Central Teaching Lab: PC Teaching Centre BLUE ZONE (1 - 4pm)

-   Lecture: Time and Flows.

-   Lab: Visualising Flows in Python.

**Week 10 GF** Central Teaching Lab: PC Teaching Centre BLUE ZONE (1 - 4pm)

-   Lecture: Dashboards.

-   Lab: Dashboards with Panel.
    
**Week 11 GF** Central Teaching Lab: PC Teaching Centre BLUE ZONE (2 - 4pm)

-   Lab only: Review & Assignment II clinic.

-   **Assignment II Due (Week 11)** 30th April 2.00pm


